### ISSUE TITLE
MPS doesn't support cumsum

### ISSUE THREAD

**Issue by thomasahle** [normal-computing/outlines#196]
I edited `examples/parsing.py` to use `device=mps`. But it doesn't run because "MPS does not support cumsum op with int64 input":

```
ahle@Thomass-MacBook-Pro ~/outlines (main)$ py -m examples.parsing
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/ahle/outlines/examples/parsing.py", line 113, in <module>
    outputs = model.generate(
              ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/generation/utils.py", line 1522, in generate
    return self.greedy_search(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/generation/utils.py", line 2336, in greedy_search
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/models/codegen/modeling_codegen.py", line 632, in prepare_inputs_for_generation
    position_ids = attention_mask.long().cumsum(-1) - 1
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: MPS does not support cumsum op with int64 input
```

**Comment by rlouf** [comment]
I found this relevant issue on the PyTorch repo: https://github.com/pytorch/pytorch/issues/96610
