### ISSUE TITLE
Syntax errors in README examples

### ISSUE THREAD

**Issue by arnavgarg1** [normal-computing/outlines#219]
I think the README might be outdated with the new 0.0.8 release

**Comment by arnavgarg1** [comment]
```
>>> import outlines.text.generate as generate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.8/site-packages/outlines/__init__.py", line 4, in <module>
    from outlines.text import prompt
  File "/opt/homebrew/lib/python3.8/site-packages/outlines/text/__init__.py", line 2, in <module>
    from .generate import continuation
  File "/opt/homebrew/lib/python3.8/site-packages/outlines/text/generate/__init__.py", line 2, in <module>
    from .regex import choice, float, integer, json, regex
  File "/opt/homebrew/lib/python3.8/site-packages/outlines/text/generate/regex.py", line 11, in <module>
    from outlines.text.json_schema import build_regex_from_schema
  File "/opt/homebrew/lib/python3.8/site-packages/outlines/text/json_schema.py", line 204
    match step:
          ^
SyntaxError: invalid syntax
```

Not sure what's going on here, maybe its a jsonschema package version mismatch? I'm on `4.6.2`

**Comment by rlouf** [comment]
Thank you for opening an issue! It looks like a Python version issue. Make sure to install Python >= 3.10. Let me know if examples still fail.

**Comment by davidberenstein1957** [comment]
Hi, I noticed this too, but I would say rewriting the code might be better than forcing people to install 3.10. https://github.com/normal-computing/outlines/issues/234

**Comment by davidberenstein1957** [comment]
I can create a PR for this if you allow me to work on it.
